### ISSUE TITLE
v2 documentation

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#448]
## To-dos
Remaining TODO items after completing other v2 changes (see #447):
- [x] update `conf.py` when the full v2 module is moved over
- [x] update CLI tutorials when that code is finished
- [x] place in appropriate hyperlinks
- [x] complete python usage tutorial
- [x] amend `.readthedocs.yml`. I don't think anything actually needs to be done here, but I make no promises that it's correct.

**Comment by kevingreenman** [comment]
closed by #467
