### ISSUE TITLE
[TODO]: improve serialization/saving mechanism

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#591]
Opening up an issue to centralize discussion because I've been commenting on this topic in a number of PRs. We should think carefully about structuring the outputs of the chemprop CLI. Irrespective of the high-level directory organization (re #581: separating by ensemble members then further segmenting by model fold), we should be clear about what we _need_ to save and _why_ it's necessary. We should also think about what might be nice to have. This will help guide future discussion about structuring the outputs of these commands.

---

## `chemprop train`
**Needs**
- model architecture and weights
  per #585 and #589, we don't actually need a model checkpoint to serve the model at some point in the future. Not only is this preferable from a disk space perspective (because you don't need to store the gradients and the optimizer state), but it's also more portable.
- input and output transforms
  models are constructed on the assumption that inputs and outputs are normalized. For serving, we would need to transform new inputs into the model's expected domain and the outputs back into the expected prediction range to make them interpretable. We could think about making these both part of the model architecture later, but for now they're not.
- checkpoints
  In the event that a user doesn't want checkpoints for whatever reason, they should be able to **opt-out**.
- the command config
  Not strictly necessary, but you can't actually resume training from a checkpoint if you don't store the recipe to recreate the training data.

**Nice-to-haves**
- the global random seed used
  This could be nice if we wanted to replicate a training run for whatever reason. It's not strictly necessary
- the training splits
 unnecessary if the model is just being served, but it's good to give users the option. This should be an **opt-in**
- summary statistics
  it's pretty easy to calculate summary statistics for each split with `pandas` (e.g., MSE, pearson $r$, spearman $\rho$ for regression). Most users will likely be using these to evaluate their models anyways, so we can just provide them when they **opt-in** (e.g., by providing a `--summary` flag)
- individual predictions
  similar to the above for analyzing training performance at a more granular level

## `chemprop predict`
**Input needs**
- model architecture and weights
- input and output transforms

**Output needs**
- predictions

**Comment by davidegraff** [comment]
also related to #512

**Comment by KnathanM** [comment]
Here are some thoughts from our dev meeting today and @kevingreenman and @hwpang, correct me if I'm wrong.

1. Because we are using the lightning framework, the model needs to have at least the output scaler inside of it at the lastest when we run `trainer.test(model, test_loader)[0]`. The simplest way to do this could be to save the output scaler in the model and leave it there instead of saving it as a separate file. Then it could make sense to save all the scalers together inside the model as in [v1](https://github.com/chemprop/chemprop/blob/master/chemprop/utils.py#L408). This also has the added benefit that Chemprop users don't have to be careful when using the scalers (input, output, features) in prediction, as those are handled automatically for them. 

2. The log files can default to a single location with WARN verbosity. There should be separate outputs from training that record the arguments used during training in structured format (args.json in v1) and that record the progress of the training (loss, etc.) so that users can either watch their training in real time or inspect how it went after the fact.  

3. Training runs should default to output into a new timestamped directory for each run inside of the current working directory (with the option to specify a different directory for the timestamped directories to go. 

4. Prediction and v1_to_v2 model converting can overwrite (i.e. if there is already data_preds.csv, we can replace it without warning). If a user is trying to get multiple different predictions (say from multiple models), then they should be doing a better job giving their output more descriptive names.

**Comment by KnathanM** [comment]
As I wrote this up, I also had two more thoughts. 
1. While the training splits should be opt-in, the sizes of the splits are relevant for experiments that test how much data is needed to plateau learning and are like the args so should go into `args.json`. 
2. The record of the progress of the training wouldn't be needed if the user only cares about the final model. There should be a way to turn that recording off. I also am open to this being opt-in if more often users don't care about the loss during training.

**Comment by davidegraff** [comment]
> 1. Because we are using the lightning framework, the model needs to have at least the output scaler inside of it at the lastest when we run `trainer.test(model, test_loader)[0]`. The simplest way to do this could be to save the output scaler in the model and leave it there instead of saving it as a separate file. Then it could make sense to save all the scalers together inside the model as in [v1](https://github.com/chemprop/chemprop/blob/master/chemprop/utils.py#L408). This also has the added benefit that Chemprop users don't have to be careful when using the scalers (input, output, features) in prediction, as those are handled automatically for them.

I agree in part after thinking about this a little more. The key desideratum IMO is that a model state file (`.pt`) should be a _subset_ of a checkpoint file (`.ckpt`) so that an `MPNN.load_model` class method (1) shares the same signature as `MPNN.load_checkpoint` class method and (2) any valid checkpoint file is _also_ a valid input to that method. This requires a model state file contain _all_ the information necessary for loading a model, i.e., hyperparameters and weights (but not optimizer state, gradients, etc.)

> 2. The log files can default to a single location with WARN verbosity. There should be separate outputs from training that record the arguments used during training in structured format (args.json in v1) and that record the progress of the training (loss, etc.) so that users can either watch their training in real time or inspect how it went after the fact.

Users can already do this via the tensorboard logs that are written. These are separate from the `chemprop` logs. We can think about giving users the option to combine these _in the future_ (i.e., having some arguments that point the model training logs to the `chemprop` logfile.)

> 3. Training runs should default to output into a new timestamped directory for each run inside of the current working directory (with the option to specify a different directory for the timestamped directories to go.

The training CLI should write a structured _directory_ given a specified path. If none is provided, we should write to `$PWD/chemprop_output/MODE/TIMESTAMP`. I'm not sold on the name `chemprop_output` as the top-level directory, but just writing to `train` in the case of `chemprop train` is a poor top-level name IMO. We should not separate out the output directory into multiple parts (e.g., `--root` + `--stem`) because this will be overly cumbersome for many users and can be unclear on what the actual output directory ends up as. If a user _wants_ to name their directory a simple timestamp, then they're perfectly capable of doing it themselves using simple command-line utilities (e.g,. `date +%Y-%m-%dT%H-%M-%S`). For prediction, we can write to `chemprop_output/predict/$( basename $INPUT .csv )_preds.csv`. I feel similarly here about the need for a good default top-level directory name.

> 4. Prediction and v1_to_v2 model converting can overwrite (i.e. if there is already data_preds.csv, we can replace it without warning). If a user is trying to get multiple different predictions (say from multiple models), then they should be doing a better job giving their output more descriptive names.

We should be consistent with behavior across multiple modes IMO. If there's a name collision, we shouldn't (i) silently redirect output and (ii) assume we know better than what a user asks for. If they provide a directory that already exists in `chemprop train`, we should overwrite any files that possibly overlap as long as we give them a safe mode: `--no-ovewrite` to use

**Comment by davidegraff** [comment]
> 1. While the training splits should be opt-in, the sizes of the splits are relevant for experiments that test how much data is needed to plateau learning and are like the args so should go into `args.json`.

Agreed. I put the "config" into the "needs" section above. It's not strictly necessary for model serving, but it _is_ necessary to resume model training

> 2. The record of the progress of the training wouldn't be needed if the user only cares about the final model. There should be a way to turn that recording off. I also am open to this being opt-in if more often users don't care about the loss during training.

I'm assuming you mean training logs, and I agree with the caveat that it should be _opt-out_. We can disable training logging by specifying `log_every_n_steps=0` in the `Trainer`. All we need to do is expose this option to the user. A future feature that would be nice is enable training log customization to use any [logger that lightning supports](https://lightning.ai/docs/pytorch/stable/extensions/logging.html)

**Comment by KnathanM** [comment]
I think these are great points and ideas. Two more thoughts/questions:
1. Currently specifying just the flag `--logfile` sends the logfile to `{LOG_DIR}/MODE/{NOW}.log` instead of `{LOG_DIR}/{NOW}.log`. It could be useful to have specifying the flag send the logfile to the same directory as the rest of the Chemprop output. That way users who want to watch the logfile without leaving the output directory can just use the flag without having to specify the path. But in the current set up, logging starts before we have processed the args so we don't know where the output will be at that point. So, what do you think about that behavior of specifying just the flag, and if you think it is reasonable, is there a good way to get the output dir in time to start logging? I have thought of three ways but all feel inelegant. The start of logging could be moved into each subcommand, but that repeats code. We could parse the output arg in main.py but then the code for a subcommand isn't self contained and depends on main.py. We could add a classfunction to get the output dir to the subcommands and call it from main.py similar to `func`. That has the advantage of retaining segregation of the code but it makes the subcommands more complex. 
2. I expect most of the time that users specify a logfile path, they will also want the logging output to be more verbose (why intentionally put the logfile somewhere only for it to be empty because no errors were thrown). So `--logfile <path> -vv` may be a common combination. It could be useful to combine the two, such that specifying a path for the logfile automatically sets the logging level to INFO. But my counterthought is that prevents users to both move the logfile and set the logging level to WARN, if they had a reason to do so.

**Comment by KnathanM** [comment]
I like the framework of its more important for commands to be idiomatic than concise.

> Probably the easiest solution right now is (2), promoting output to an argument in main.py.

Two concerns with promoting output:
1. **Specifying defaults.** Having separate output options for each mode allows them to have their own help message. Prediction defaults to appending "_preds.csv" to the base name of the input. For v1_to_v2 model conversion, the default is different and related to the suffix ".ckpt". If there is only one global output option, either the help message for the global option would need to be all inclusive (and long), or we would need some other way to tell user what the defaults are. 
2.  **Directory vs file.** For training, `output` means the directory where output goes. For prediction, it means the file to write output to. `handler = logging.FileHandler(str(Path(args.output) / chemprop.log))` doesn't work if args.output is supposed to be a file. A solution is to check which mode is running `if mode=="train": ` and adjust accordingly. 

That said, promoting output is my favorite option because the CLI feels less complicated when each mode doesn't have its own output and I think the issues I raise above can be addressed. The same could be said for having only one global input argument. (The one complication to a global input argument is the input for training and prediction were given different names in v1. I think maintaining backwards compatibility on that core argument is valuable, but then it complicates the `chemprop -h` to have multiple aliases for the same input command.)

**Comment by KnathanM** [comment]
> Each mode can just override `--output`. That is when you have the following block of code:

This isn't possible with argparse. Your example gives `argparse.ArgumentError: argument --foo: conflicting option string: --foo`. 
It also isn't possible with subparsers. Minimum example:
```
import argparse
parser = argparse.ArgumentParser(add_help=False)
parser.add_argument('-o', help='parent argument')
subparsers = parser.add_subparsers()
subparser = subparsers.add_parser('child', parents=[parser])
subparser.add_argument('-o', help='child argument')
print(parser.parse_args())
```

That's okay though because in the current version, all of the subparsers exist at the same time and the one that is called (for example, train) will have its arguments parsed at the same time as the parent parser. So when we have access to `args.logfile` we would also have access to `args.output_dir`. 

The issue is that the subcommand args don't get processed until `func(args)`. So while we have the line `logfile = Path(LOG_DIR / mode / f"{NOW}.log" if logfile is None else logfile)` in main.py to set the default logfile, we don't have something like `args.output_dir = args.output_dir or <default>` until later. It is this processing that would need to be promoted to main.py, not the specification of the argument (`.add_arguement()`), but the processing is dependent on the mode (what suffix to add, etc.) and feels like it belongs in the subcommand's file (e.g. train.py) where it currently is. 

Right now I'm feeling it is more trouble than it is worth to have just the flag `--logfile` send the log to `$OUTPUT/chemprop.log`.  I think requiring the user to give the path `--log chemprop.log` if they want to see the log file where they are is reasonable. This also reduces the four logging modes to three and we can use simple flag mechanics again (no flag -> stdout, just the flag -> Inside LOG_DIR, flag with path -> log at the path).

**Comment by mefortunato** [comment]
Where does feature generation come into play when it comes to serialization? It might be nice to have a `chemprop.models.MPNN.predict_from_smiles` method or something like it that handles featurization _as it was performed at the time the saved model was trained_. Otherwise, at the time of serving, the Python code used for featurization must be copied along with the saved checkpoint. Is this consideration in scope?

**Comment by davidegraff** [comment]
That's considered out of scope in v2 as there's a logical separation between the MPNN and molecules now. It's not standard in pytorch to tightly couple your data transform ("featurization scheme") and your function (`nn.Module`). We've opted to adopt this object model and limit the logical scope of the MPNN now. That is, the only notion of "molecules" inside the MPNN code is now only inside the docstrings and it has no dependencies on "molecular" logic. Per your use case, there's only a couple of featurization args enabled via the CLI (see [here](https://github.com/chemprop/chemprop/blob/fc036fb9fb3b7d9eda72341d719cc27eb4df0a1f/chemprop/cli/common.py#L46-L119)), and only a subset of those must be copied from `chemprop train` to `chemprop predict`. If you are asking about a more custom featurization scheme (i.e., augmenting the atom/bond-featurizers), then at that point you're already interacting with the code from the module level and it's almost impossible to find a one-size-fits-all solution once you're there. I'm happy to chat about some possible options, however.

**Comment by mefortunato** [comment]
> Per your use case, there's only a couple of featurization args enabled via the CLI (see [here](https://github.com/chemprop/chemprop/blob/fc036fb9fb3b7d9eda72341d719cc27eb4df0a1f/chemprop/cli/common.py#L46-L119)), and only a subset of those must be copied from `chemprop train` to `chemprop predict`.

I am considering a use case of serving the model via a web API, or torchserve, etc., not predicting from the command line. I have found it very advantageous in my work to be able to load a model from a checkpoint and then predict from the input that will be provided to the API endpoint (smiles strings). It's not really the business of the API to know/understand what happened during experimentation.

> That is, the only notion of "molecules" inside the MPNN code is now only inside the docstrings and it has no dependencies on "molecular" logic.

The first argument to the forward method is a `BatchMolGraph` which is very specific to ChemProp's featurization of a molecule. I think you could try to make this argument about the encoder (it could be abstracted away from molecular logic, although it too has references to molecular data), but the outer model wrapper is seemingly designed to work with chemical data - is there intention to generalize the code to work with other types of data? Wouldn't this make the case even stronger for serializing featurization alongside a model as the options to featurize increase? There already exist greater than 1 featurization methods in ChemProp so this seems like it deserves consideration.

> If you are asking about a more custom featurization scheme (i.e., augmenting the atom/bond-featurizers), then at that point you're already interacting with the code from the module level and it's almost impossible to find a one-size-fits-all solution once you're there.

One of the great benefits I see from this refactor to v2 is the increased modularity and flexibility to enable more experimentation. While it is true during this experimentation you'll be interacting with the code, it is the use of the model afterwards that would benefit from portability of featurization along with the model. If prediction is intended to use a pytorch lightning trainer and a dataloader, serializing an object that can perform input (smiles) -> dataloader along with the model seems like a generic solution that would presumably work quite well.

**Comment by davidegraff** [comment]
> I am considering a use case of serving the model via a web API, or torchserve, etc., not predicting from the command line. I have found it very advantageous in my work to be able to load a model from a checkpoint and then predict from the input that will be provided to the API endpoint (smiles strings). It's not really the business of the API to know/understand what happened during experimentation.

And I would argue it's not the business of a pytorch module to know the non-differentiable transforms that got. The only way this worked in v1 was due to the _lack_ of flexibility in the featurization. Though it was theoretically possible to alter the featurization scheme, the reliance on global state meant that any attempt to serialize the model's bytecode via pickle (which `torch.save` relies on internally) would mean that it would break at deploy-time. That is, if you _managed_ to alter the featurization scheme in an experiment, saved your model, and deployed it, the deploy-time featurization scheme **would not** be correct. The flexibility of torchserve as a package hid these problems by allowing users to deploy arbitrary python objects and call the models, but the correct way would be to deploy the model inside a [handler](https://pytorch.org/serve/custom_service.html#custom-handlers) which stores the featurization scheme as well. 

> The first argument to the `forward` method is a `BatchMolGraph` which is very specific to ChemProp's featurization of a molecule. I think you could try to make this argument about the encoder (it could be abstracted away from molecular logic, although it too has references to molecular data), but the outer model wrapper is seemingly designed to work with chemical data - is there intention to generalize the code to work with other types of data? Wouldn't this make the case even stronger for serializing featurization alongside a model as the options to featurize increase? There already exist greater than 1 featurization methods in ChemProp so this seems like it deserves consideration.

The only notion of molecules in a `BatchMolGraph` is in the name. If you look at the object model, you'll see that it's literally just a graph:

```python
class BatchMolGraph:
    V: Tensor = field(init=False)
    E: Tensor = field(init=False)
    edge_index: Tensor = field(init=False)
    rev_edge_index: Tensor = field(init=False)
    batch: Tensor = field(init=False)
```

The notion of molecules only comes in via the transform scheme: `MolGraphFeaturizer : Chem.Mol -> MolGraph`. At the point you've converted a molecule to a graph, there's no difference between the D-MPNN of chemprop and any other pytorch MPNN. This is intended via the v2 rewrite to separate concerns of data transforms and tensor operations.

> One of the great benefits I see from this refactor to v2 is the increased modularity and flexibility to enable more experimentation. While it is true during this experimentation you'll be interacting with the code, it is the use of the model afterwards that would benefit from the portability of featurization along with the model. If prediction is intended to use a pytorch lightning trainer and a dataloader, serializing an object that can perform input (smiles) -> dataloader along with the model seems like a generic solution that would presumably work quite well.

My point is that serialization is not entirely trivial here and that just because it happened to work in v1 does not mean it was actually working. To get it working properly we'll need to work on a serialization scheme for the featurizer that's more sophisticated than just attaching it to the model.

**Comment by mefortunato** [comment]
Irrespective of chemprop v1, I have my own personal development very similar to this v2 refactor using pytorch lightning that I began before this effort started, and I do not have any issues serializing a Python callable object to store featurization functionality alongside model state - I'm probably missing the nuance that is making this non-trivial.

With that said, I'm very motivated to discard my parallel effort, and I'm happy to adopt more standard best practices, so if the featurization is not going to be serialized with the checkpoint itself, an example training workflow that simultaneously saves an "artifact" (being intentionally very vague here) for deployment would be greatly appreciated. Should this be a separate issue then?

**Comment by mefortunato** [comment]
That is quite an interesting concern, and it's very ambitious to attempt to address this type of theoretical security vulnerability. I would just echo the desire for an example of appropriate artifact generation capable of reproducing both the data featurization (from SMILES) and a forward pass through a chemprop trained model.

**Comment by KnathanM** [comment]
In an effort to move towards closing this issue, here is my summary:

Saving Needs:
- [X] Model architecture and weights
- [ ] Input and ouput transforms #726
- [ ] Opt out of checkpoints - Not started, probably a v2.1 thing at this point.
- [ ] Config file #775

Saving Nice-to-haves
- [ ] Random seeds used - I'm not sure this is necessary since we decided on `pl.Trainer(deterministic=False)` to be the default. Even if you have the seeds used, you couldn't exactly replicate the training. 
- [X] The training splits - Saved as smiles, not as indices
- [ ] summary statistics - Probably a v2.1 thing at this point
- [X] individual predictions - Currently predictions on the test set can be saved. Additionally using chemprop predict produces separate output for each model in an ensemble. Combining them is a v2.1 thing.

From the discussion by @mefortunato and @davidegraff, it looks like an example of showing how to serve a Chemprop model via a web API would be useful. I feel this is something that many users (including myself) would benefit from. Even though a specific featurizer is needed to prepare input data for inference, the featurizer is not considered part of the model in deployment. Instead the `BaseHandler` from `torchserve` defines a framework to `initialize` the model, `preprocess` the data with the featurizer used to train the model, and run `inference` on the preprocessed data using the model. I believe this is all possible without changes to the current Chemprop code, so will table making this example until v2.0 is released early next week.

**Comment by JacksonBurns** [comment]
@KnathanM disabling checkpoints was implemented https://github.com/chemprop/chemprop/pull/1014 and summary statistics were added https://github.com/chemprop/chemprop/pull/882 so we can close this I believe?

**Comment by KnathanM** [comment]
Thanks for seeing that
