### ISSUE TITLE
[TODO][V2]: Various documentation and benchmarking tasks.

### ISSUE THREAD

**Issue by joelnkn** [chemprop/chemprop#648]
**Notes**

- [ ] Write some useful example notebooks for Chemprop users: https://github.com/chemprop/chemprop/issues/556#issuecomment-1917936170
- [ ] Add new example .csv files for users to test Chemprop features: eg. Smiles document with molecule features and targets.
- [ ] Rewrite Chemprop benchmark scripts to run on v2

**Comment by KnathanM** [comment]
> **Notes**
> 
> * [ ]  Write some useful example notebooks for Chemprop users: [[TODO]: Add example notebooks to the docs #556 (comment)](https://github.com/chemprop/chemprop/issues/556#issuecomment-1917936170)
> * [ ]  Add new example .csv files for users to test Chemprop features: eg. Smiles document with molecule features and targets.
> * [ ]  Rewrite Chemprop benchmark scripts to run on v2

Example notebooks are tracked by another issue.
I think the new example .csv files is fulfilled by the data in tests/data/regression/mol/
This is done and will be published soon.
