### ISSUE TITLE
[TODO]: v2 documentation updates

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#701]
**Notes**

- [x] missing jupyter notebook tutorial link on homepage
- [x] need to add note/warning to the installation page about the torch/torch-scatter installation issues people might face even with our special instructions
- [x] need to update the instructions in the train & predict CLI pages with actual files and models in our tests folder
- [x] remove dockerfile and corresponding installation instructions for now since these don't work
- [x] some things in train might not be implemented yet (need to update [this file](https://github.com/chemprop/chemprop/blob/v2/dev/docs/source/tutorial/cli/train.rst))
